### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/driving-game#1]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] add conditional to drive function
- [x] edit condition so if car is facing east, add to left property.
- [x] edit condition so if car is facing west, subtract from left property.
- [x] edit condition so if car is facing south, add to top property.
- [x] edit condition so if car is facing north, subtract from top property.
- [x] test game, check code, fix errors, etc
