### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add location property to data model
- [x] change car position to absolute
- [x] add condition to check for space bar keydown
- [x] start interval
- [x] create function to handle moving the car
- [x] clean up code
