### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/driving-game#4]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] query DOM for car
- [x] add event listener to car
- [x] create data model that records cars direction
- [x] create css classes to handle rotation
- [x] rotate car up on keydown
- [x] rotate car left on keydown
- [x] rotate car down on keydown
- [x] rotate car right on keydown
- [x] clean up functionality
