### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by Nickolas-Hernandez** [Nickolas-Hernandez/driving-game#5]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create index, stylesheet and script files.
- [x] create html skeleton
- [x] add car to html
- [x] style background and car
